### ISSUE TITLE
How i can use

### ISSUE THREAD

**Issue by Ashish882** [fs0c1ety/SLocker#1]
How I can use this coding to make ramsomware apk file with Linux .

Plz tell me...

**Comment by raul3k** [comment]
http://bfy.tw/D0EW

**Comment by fs0c1ety** [comment]
Hi Ashish882,

As a normal application, you can open this code with Android Studio: https://developer.android.com/studio/index.html#downloads.

Please note:
SLocker is intended to be used for security research purposes only. Any other use is not the responsibility of the developer(s). Be sure that you understand and are complying with the laws in your area. In other words, don't be stupid, don't be an asshole, and use it responsibly and legally.

Regards,

**Comment by Ashish882** [comment]
Thanks to reply how I can open this code with my android device only

**Comment by fulopm** [comment]
If you can't answer these questions by yourself, you should not use this.
